BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "alcal_persona" (
	"id"	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"apellido"	varchar(100),
	"nombre"	varchar(100),
	"num_dni"	integer,
	"domicilio_calle"	varchar(100),
	"domicilio_numero"	integer,
	"telefono_1"	varchar(100),
	"telefono_2"	varchar(100),
	"telefono_3"	varchar(100),
	"observacion"	text,
	"pais_de_nacimiento"	varchar(2),
	"genero"	varchar(20),
	"tipo"	varchar(20),
	"email"	varchar(254),
	"fnac"	date
);
CREATE TABLE IF NOT EXISTS "alcal_estudiante" (
	"legajo"	integer NOT NULL,
	"persona_ptr_id"	integer NOT NULL UNIQUE,
	"activx"	bool,
	"orden"	integer,
	"libro"	varchar(5),
	"folio"	integer,
	"anio_ingreso"	integer,
	"grupo_tec"	integer,
	"ficha_de_inscripcion"	bool,
	"foto_dni_estudiante"	bool,
	"foto_dni_estudiante_archivo"	varchar(100),
	"foto_dni_responsable"	bool,
	"partida_de_nacimiento"	bool,
	"vacunas"	bool,
	"certificado"	bool,
	"url_foto"	varchar(200),
	"archivo_de_seguimiento"	varchar(200),
	"porcentaje_beca"	integer,
	"adeuda_id"	integer,
	"curso_id"	integer,
	"responsable_id"	integer,
	"vinculo"	varchar(50),
	PRIMARY KEY("legajo"),
	FOREIGN KEY("responsable_id") REFERENCES "alcal_padre"("persona_ptr_id") DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("curso_id") REFERENCES "alcal_curso"("id") DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("adeuda_id") REFERENCES "alcal_documentacion"("id") DEFERRABLE INITIALLY DEFERRED,
	FOREIGN KEY("persona_ptr_id") REFERENCES "alcal_persona"("id") DEFERRABLE INITIALLY DEFERRED
);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (24,'Albella ','Elsa Dolores','11.492.836',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ealbella@sagradoalcal.edu.ar','1955-01-23');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (25,'Alfaro ','Cecilia Maria','17.937.961',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'calfaro@sagradoalcal.edu.ar','1966-11-01');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (26,'Aloi ','Federico','36.528.600',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'faloi@sagradoalcal.edu.ar','1991-10-30');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (27,'Altamiranda ','Esteban','27.170.682',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'ealtamiranda@sagradoalcal.edu.ar','1979-01-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (28,'Altamiranda ','Leandro','26.371.223',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'laltamiranda@sagradoalcal.edu.ar','1977-11-13');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (29,'Alvarenga ','Erika','32.999.831',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ealvarenga@sagradoalcal.edu.ar','1987-03-29');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (30,'Amigo ','Mirta Susana','17.302.664',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'mamigo@sagradoalcal.edu.ar','1964-10-16');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (31,'Báez ','Marcelo Adolfo','23.158.996',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'mbaez@sagradoalcal.edu.ar','1973-08-18');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (32,'Barakian  ','Layla Belen','33.118.417',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'lbarakian@sagradoalcal.edu.ar','1987-04-26');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (33,'Batlle ','Leandro Ernesto','24.178.975',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'lbatlle@sagradoalcal.edu.ar','1975-01-03');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (34,'Berone ','Maximiliano Ezequiel','29.363.484',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'mberone@sagradoalcal.edu.ar','1982-06-12');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (35,'Bonifacini ','Elba Sandra','17.039.073',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'sbonifacini@sagradoalcal.edu.ar','1964-04-02');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (36,'Bordón ','José Victor','23.906.881',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'jbordon@sagradoalcal.edu.ar','1974-04-25');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (37,'Britez Neira ','Guillermo Hernan','35.373.917',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'gbritez@sagradoalcal.edu.ar','1991-02-10');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (38,'Bugna ','Gisella Carla','36.724.133',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'gbugna@sagradoalcal.edu.ar','1992-02-27');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (39,'Cáceres ','Mario Nicolás','35.901.972',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'ncaceres@sagradoalcal.edu.ar','1991-04-12');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (40,'Cajaraville ','Noelia Paola','29.906.404',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ncajaraville@sagradoalcal.edu.ar','1982-11-10');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (41,'Calviello ','Matías Damian','32.669.725',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'mcalviello@sagradoalcal.edu.ar','1986-11-13');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (42,'Carballo ','Matías Exequiel','30.448.248',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'mcarballo@sagradoalcal.edu.ar','1983-08-14');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (43,'Carrizo  ','Cayetano Jesus ','35.999.055',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'ccarrizo@sagradoalcal.edu.ar','1991-04-02');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (44,'Chiesa ','Leonardo Alejandro','33.557.737',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'lchiesa@sagradoalcal.edu.ar','1988-03-23');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (45,'Cordoba','Pablo Damian','33.362.053',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'pcordoba@sagradoalcal.edu.ar','1987-10-16');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (46,'Cortés ','Martina','35.367.137',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'mcortes@sagradoalcal.edu.ar','1990-11-14');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (47,'Crippa ','Andrés Miguel','34.454.018',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'acrippa@sagradoalcal.edu.ar','1989-02-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (48,'Crismai ','Natalia Andrea','24.856.517',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ncrismai@sagradoalcal.edu.ar','1975-10-14');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (49,'Cruz ','Camila','34.401.422',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ccruz@sagradoalcal.edu.ar','1989-03-04');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (50,'Cuesta ','Federico Martin','33.740.804',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'fcuesta@sagradoalcal.edu.ar','1988-07-23');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (51,'De Bonis ','Esteban Miguel','29.502.721',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'edebonis@sagradoalcal.edu.ar','1982-05-04');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (52,'Exposto ','Emiliano','33.982.204',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'eexposto@sagradoalcal.edu.ar','1988-09-09');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (53,'Ferrero ','Maria Victoria ','29.318.467',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'vferrero@sagradoalcal.edu.ar','1982-02-03');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (54,'Flores ','Rafael Alejandro','20.504.750',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'raflores@sagradoalcal.edu.ar','1968-11-14');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (55,'García ','Yanina Mariel','27.788.671',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ygarcia@sagradoalcal.edu.ar','1979-12-04');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (56,'Giaimo ','Paula Jimena','25.632.269',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'pgiaimo@sagradoalcal.edu.ar','1976-09-01');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (57,'González ','Maria Lorena ','31.032.584',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'lgonzalez@sagradoalcal.edu.ar','1984-08-24');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (58,'Gubitosi ','Florencia Dulcinea ','34.146.389',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'dgubitosi@sagradoalcal.edu.ar','1988-10-23');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (59,'Guerrero ','Ana Carina','23.170.224',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'cguerrero@sagradoalcal.edu.ar','1973-05-26');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (60,'Herrera ','Patricia Daniela','30.557.204',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'pherrera@sagradoalcal.edu.ar','1983-10-13');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (61,'Kulik ','Andres','13.697.848',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'akulik@sagradoalcal.edu.ar','1957-07-29');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (62,'Laborde ','Paula Gabriela','31.000.127',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'plaborde@sagradoalcal.edu.ar','1984-07-22');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (63,'Leonik ','Karina Lorena','23.060.738',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'kleonik@sagradoalcal.edu.ar','1973-02-17');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (64,'Lezcano  ','Gastón Leopoldo','23.969.512',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'glezcano@sagradoalcal.edu.ar','1974-04-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (65,'Lotero ','Ivana Araceli','37.980.021',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ilotero@sagradoalcal.edu.ar','1994-05-16');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (66,'Luna ','Maria Alejandra ','39.656.105',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'aluna@sagradoalcal.edu.ar','1996-06-20');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (67,'Márquez ','Rodrigo Sebastian ','30.436.014',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'rmarquez@sagradoalcal.edu.ar','1983-07-19');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (68,'Martín ','Luciana','29.461.709',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'lmartin@sagradoalcal.edu.ar','1982-05-25');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (69,'Morales ','Lorena Noemi','30.664.214',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'lmorales@sagradoalcal.edu.ar','1983-12-18');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (70,'Olmedo',' Juan Pablo','32.198.998',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'jolmedo@sagradoalcal.edu.ar','1980-03-05');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (71,'Pabón ','Andrea Carmen','32.123.730',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'apabon@sagradoalcal.edu.ar','1986-01-31');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (72,'Papaianni ','Mariano Emmanuel Raul','32.359.854',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'mpapaianni@sagradoalcal.edu.ar','1986-05-27');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (73,'Perasso ','Tomás Agustin','30.055.444',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'tperasso@sagradoalcal.edu.ar','1983-03-07');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (74,'Puente ','Maria Soledad','31.050.362',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'spuente@sagradoalcal.edu.ar','1984-08-11');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (75,'Rodríguez ','Heber Hernan','29.592.661',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'hrodriguez@sagradoalcal.edu.ar','1982-06-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (76,'Rojas ','Claudio Alberto','26.822.193',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'crojas@sagradoalcal.edu.ar','1978-10-02');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (77,'Romero ','Juan Pablo','30.408.797',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'jromero@sagradoalcal.edu.ar','1983-07-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (78,'Sen ','Estanislao','12.667.279',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'esen@sagradoalcal.edu.ar','1956-07-01');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (79,'Sequeira ','Sabrina Soledad','31.977.296',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'ssequeira@sagradoalcal.edu.ar','1985-10-20');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (80,'Sierra Bueno ','Camila Micaela','34.748.211',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'csierrabueno@sagradoalcal.edu.ar','1989-09-03');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (81,'Sierra Bueno ','Andrea Alejandra','92.898.558',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'asierrabueno@sagradoalcal.edu.ar','1985-08-30');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (82,'Taliercio ','Maria Gracia','13.992.303',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'gtaliercio@sagradoalcal.edu.ar','1959-09-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (83,'Ughetti ','Javier Martin','23.906.541',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'jughetti@sagradoalcal.edu.ar','1974-04-05');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (84,'Villalba ','Lucia Carolina','22.983.335',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'cvillalba@sagradoalcal.edu.ar','1972-12-17');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (85,'Villalonga ','Jorge Horacio','16.937.883',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'jvillalonga@sagradoalcal.edu.ar','1963-09-20');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (86,'Vitullo ','Ezequiel','38.066.241',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'evitullo@sagradoalcal.edu.ar','1994-02-01');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (87,'Martinez','Gastón',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'gmartinez@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (88,'Gonzales ','Claudia','20.383.336',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,NULL,'1968-12-03');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (89,'Oliva','Anabella Yasmín',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'aoliva@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (90,'Moyano','Sebastián',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'smoyano@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (91,'Valenzuela Colman','Gustavo Andrés','35.972.430',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'gvalenzuela@sagradoalcal.edu.ar','1991-05-05');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (92,'Prieto','Florencia','37.557.835',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'florencia.prieto@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (93,'Peresson','Arianna',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'aperesson@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (94,'Acevedo','María Noel',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'macevedo@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (95,'Gómez','Diego','24.312.730',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'dgomez@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (96,'Del Corro','Miguel Calixto','25.755.100',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'mdelcorro@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (97,'Blanco','Marisol','23.768.514',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'mblanco@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (98,'Trombiero','Solange',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'strombiero@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (99,'Cáceres','Lilian Soledad','37.120.267',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'scaceres@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (100,'Gómez','Carlos Andrés','33.944.642',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'cgomez@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (101,'Pruebas','Alcal',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'pruebas@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (102,'Martín ','Soledad Gabriela','34.490.654',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'smartin@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (103,'Spigariol','Lucas','  47.490.634 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,NULL,NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (104,'De La Fuente','Gustavo','  47.576.105 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,NULL,NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (105,'Palumbo','Nahuel','  47.485.915 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,NULL,NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (106,'Torres','Adriana','  47.495.140 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,NULL,NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (107,'Abálsamo','Manuel','  47.576.371 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,NULL,NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (108,'Demonte','Carolina','  47.884.424 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'cdemonte@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (109,'Sabatini','Natalia','  47.389.333 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'nsabatini@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (110,'Navas','Pablo','  47.802.363 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masculino',NULL,'pnavas@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (111,'Pontoriero','Lina Luján','  47.868.475 ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Femenino',NULL,'lpontoriero@sagradoalcal.edu.ar',NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (112,'ALINCASTRO','Nicole Nerea Trinidad','  47.490.634 ','M. PEDRAZA',NULL,'42280151',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'nicole.alincastro@sagradoalcal.edu.ar','2006-10-08');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (113,'BARRIENTOS','Mirko Benjamín','  47.576.105 ','Obón',NULL,'1561081363',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'mirko.barrientos@sagradoalcal.edu.ar','2006-12-18');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (114,'BUENO','Luna Abigail','  47.485.915 ','Madero',NULL,'1554266120',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'luna.bueno@sagradoalcal.edu.ar','2006-08-29');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (115,'CARRIZO','Agostina Milagros','  47.495.140 ','MADERO 2648',NULL,'1564994764',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'agostina.carrizo@sagradoalcal.edu.ar','2006-10-24');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (116,'DURAN','Ámbar Jade','  47.576.371 ','M. PEDRAZA 3791',NULL,'42186270',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'ámbar.duran@sagradoalcal.edu.ar','2007-01-11');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (117,'FERNANDEZ PATTETA','Román Agustín','  47.884.424 ','M.PEDRAZA',NULL,'1523253550',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'román.fernandez@sagradoalcal.edu.ar','2006-12-11');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (118,'FLORES','Nahuel Lautaro','  47.389.333 ','JOSE M. MORENO',NULL,'42180421',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'nahuel.flores@sagradoalcal.edu.ar','2006-07-05');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (119,'GIGLIO','Sofía Elizabeth','  47.802.363 ','OTAMENDI 457',NULL,'1532801277',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'sofía.giglio@sagradoalcal.edu.ar','2007-03-02');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (120,'GIMENEZ','Valentino Maximiliano','  47.868.475 ','E.CASTRO 3913',NULL,'1553846984',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'valentino.gimenez@sagradoalcal.edu.ar','2007-04-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (121,'GOMEZ','Mathías Alejandro','  46.502.175 ','M.MAZA 3815',NULL,'1556230543',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'mathías.gomez@sagradoalcal.edu.ar','2005-05-10');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (122,'GRIGORIEW ENCINA','Nahiara Jacqueline','  47.802.713 ','M.PEDRAZA 4072',NULL,'1534229584',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'nahiara.grigoriew@sagradoalcal.edu.ar','2007-04-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (123,'JARA','Axel Gabriel','  47.802.767 ','RINCON 2148',NULL,'1550104114',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'axel.jara@sagradoalcal.edu.ar','2007-05-17');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (124,'LOPEZ ALFONZO','Héctor Fabián','  47.802.648 ','ARISTÓBULO DEL VALLE',NULL,'1527596668',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'héctor.lopez@sagradoalcal.edu.ar','2007-05-17');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (125,'LUNA','Valentina Anahí','  47.556.217 ','TALCAHUANO 293',NULL,'1557266889',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'valentina.luna@sagradoalcal.edu.ar','2006-10-11');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (126,'MALDONADO','Nicolás Ezequiel','  47.759.129 ','E.CASTRO 4094',NULL,'1566564252',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'nicolás.maldonado@sagradoalcal.edu.ar','2007-02-23');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (127,'MIRANDA','Sasha Serena','  47.702.319 ','M.PEDRAZA 3796',NULL,'1524999401',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'sasha.miranda@sagradoalcal.edu.ar','2007-01-26');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (128,'OJEDA','Kiara Milena','  47.429.564 ','YATAY 2313',NULL,'1523164286',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'kiara.ojeda@sagradoalcal.edu.ar','2006-07-24');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (129,'ORTEGA','Melany Abril','  47.566.529 ','M.MAZA 3718',NULL,'1556244324',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'melany.ortega@sagradoalcal.edu.ar','2006-10-02');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (130,'PERALTA','Victoria Esmeralda','  47.958.173 ','GIRONDO 3581',NULL,'1536752328',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'victoria.peralta@sagradoalcal.edu.ar','2007-05-07');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (131,'PIANETTI','Mauricio Fabián Fabrizio','  48.086.318 ','CALLE 882 Nº 2270',NULL,'1560881792',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'mauricio.pianetti@sagradoalcal.edu.ar','2007-06-24');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (132,'PONCE SUAREZ','Kiara Nicole','  47.393.134 ','OTAMENDI 457',NULL,'1532801277',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'kiara.ponce@sagradoalcal.edu.ar','2006-07-06');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (133,'ROMERO','Daiana','  47.802.135 ','MAZA 3832',NULL,'42287082',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'daiana.romero@sagradoalcal.edu.ar','2007-02-27');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (134,'SUAREZ MONTERO','Mía Agustina','  47.387.632 ','MILLAN 3855',NULL,'1530821983',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'mía.suarez@sagradoalcal.edu.ar','2006-08-19');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (135,'TOSSI BERDÚN','Guadalupe Selena','  47.647.211 ','MADERO 1264',NULL,'42282317',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'guadalupe.tossi@sagradoalcal.edu.ar','2007-05-08');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (136,'UMBIDES','Alexis Joaquín','  47.749.849 ','ARISTÓBULO DEL VALLE 3668',NULL,'1536768483',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'alexis.umbides@sagradoalcal.edu.ar','2006-12-10');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (137,'VILLALBA','Abigail Florencia','  47.389.254 ','MADERO 2269',NULL,'1524999331',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'abigail.villalba@sagradoalcal.edu.ar','2018-07-16');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (138,'CARROZO','Luna Magalí','  47.032.459 ','OBÓN 2624',NULL,'1528075303',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'luna.carrozo@sagradoalcal.edu.ar','2006-08-28');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (139,'GANGALE','Maddox Joan','  47.758.772 ','C.D`LIA 4055',NULL,'42090627',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'maddox.gangale@sagradoalcal.edu.ar','2007-05-27');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (140,'GONZÁLEZ','Thiago Adrián','  47.495.295 ','MADERO 2669',NULL,'1526696867',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'thiago.gonzalez@sagradoalcal.edu.ar','2007-05-26');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (141,'PISANO','Bautista Joaquín','  47.829.458 ','MADERO 1915',NULL,'42288479',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'bautista.pisano@sagradoalcal.edu.ar','2007-03-27');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (142,'RAMIREZ','Bianca Leonela','  47.032.459 ','E.CASTRO 4015',NULL,'1569682030',NULL,NULL,NULL,'ARGENTINA','Femenino',NULL,'bianca.ramirez@sagradoalcal.edu.ar','2006-01-17');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (143,'MARECO','Elías','  95.139.844 ','OSORIO 2855',NULL,'1558924148',NULL,NULL,NULL,'ARGENTINA','Masculino',NULL,'elias.mareco@sagradoalcal.edu.ar','2006-08-25');
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (144,'De Bonis','Esteban',NULL,'California 2796',NULL,'91133847501',NULL,NULL,'',NULL,'Masculino',NULL,NULL,NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (145,'Herrera','Axel',NULL,NULL,NULL,NULL,NULL,NULL,'Le pican los ojos',NULL,NULL,NULL,NULL,NULL);
INSERT INTO "alcal_persona" ("id","apellido","nombre","num_dni","domicilio_calle","domicilio_numero","telefono_1","telefono_2","telefono_3","observacion","pais_de_nacimiento","genero","tipo","email","fnac") VALUES (146,'De Bonis','Esteban',NULL,'California 2796',NULL,'91133847501',NULL,NULL,'',NULL,'Masculino',NULL,NULL,NULL);
INSERT INTO "alcal_estudiante" ("legajo","persona_ptr_id","activx","orden","libro","folio","anio_ingreso","grupo_tec","ficha_de_inscripcion","foto_dni_estudiante","foto_dni_estudiante_archivo","foto_dni_responsable","partida_de_nacimiento","vacunas","certificado","url_foto","archivo_de_seguimiento","porcentaje_beca","adeuda_id","curso_id","responsable_id","vinculo") VALUES (12,145,1,1,NULL,NULL,2019,NULL,NULL,NULL,'1280x720_1458841066593_peppa.jpg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL);
INSERT INTO "alcal_estudiante" ("legajo","persona_ptr_id","activx","orden","libro","folio","anio_ingreso","grupo_tec","ficha_de_inscripcion","foto_dni_estudiante","foto_dni_estudiante_archivo","foto_dni_responsable","partida_de_nacimiento","vacunas","certificado","url_foto","archivo_de_seguimiento","porcentaje_beca","adeuda_id","curso_id","responsable_id","vinculo") VALUES (1234,144,1,123,NULL,NULL,2019,NULL,NULL,NULL,'PEPPA87775.jpg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,10,NULL,'Hermano');
INSERT INTO "alcal_estudiante" ("legajo","persona_ptr_id","activx","orden","libro","folio","anio_ingreso","grupo_tec","ficha_de_inscripcion","foto_dni_estudiante","foto_dni_estudiante_archivo","foto_dni_responsable","partida_de_nacimiento","vacunas","certificado","url_foto","archivo_de_seguimiento","porcentaje_beca","adeuda_id","curso_id","responsable_id","vinculo") VALUES (12344,146,1,1,NULL,NULL,2019,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,10,NULL,NULL);
CREATE INDEX IF NOT EXISTS "alcal_estudiante_responsable_id_fb2895e9" ON "alcal_estudiante" (
	"responsable_id"
);
CREATE INDEX IF NOT EXISTS "alcal_estudiante_curso_id_5190d1c1" ON "alcal_estudiante" (
	"curso_id"
);
CREATE INDEX IF NOT EXISTS "alcal_estudiante_adeuda_id_52a0d82c" ON "alcal_estudiante" (
	"adeuda_id"
);
COMMIT;
