# Generated by Django 2.2.3 on 2019-07-30 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modalidad', models.CharField(choices=[('BA', 'Bachiller'), ('TE', 'Técnico')], max_length=50)),
                ('anios', models.IntegerField(verbose_name='Años de carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('division', models.CharField(max_length=5, verbose_name='Divisón')),
                ('cursonombre', models.CharField(blank=True, default='-', max_length=5, null=True)),
                ('cursosiguiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_registro', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('antiguedad_anios', models.IntegerField(blank=True, null=True, verbose_name='Antigüedad (Años)')),
                ('antiguedad_meses', models.IntegerField(blank=True, null=True, verbose_name='Antigüedad (Meses)')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('num_dni', models.IntegerField(blank=True, null=True, verbose_name='Número de Documento')),
                ('domicilio_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio_numero', models.IntegerField(blank=True, null=True, verbose_name='Domicilio Número')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_ingreso', models.IntegerField(blank=True, null=True, verbose_name='Año de Ingreso')),
                ('fnac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('pais_de_nacimiento', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_3', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profesion', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_corto', models.CharField(blank=True, max_length=20, null=True)),
                ('carrera_docente', models.ManyToManyField(blank=True, to='alcal.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Documentaciones',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('activx', models.BooleanField(blank=True, default=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fnac', models.DateField(blank=True, null=True)),
                ('libro', models.CharField(blank=True, max_length=5, null=True)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('num_dni', models.IntegerField(blank=True, null=True)),
                ('domicilio_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio_numero', models.IntegerField(blank=True, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_3', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_ingreso', models.IntegerField(blank=True, null=True)),
                ('grupo_tec', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ficha_de_inscripcion', models.BooleanField(blank=True, null=True)),
                ('foto_dni_estudiante', models.BooleanField(blank=True, null=True)),
                ('foto_dni_estudiante_archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('foto_dni_responsable', models.BooleanField(blank=True, null=True)),
                ('partida_de_nacimiento', models.BooleanField(blank=True, null=True)),
                ('vacunas', models.BooleanField(blank=True, null=True)),
                ('certificado', models.BooleanField(blank=True, null=True)),
                ('url_foto', models.URLField(blank=True, null=True)),
                ('archivo_de_seguimiento', models.URLField(blank=True, null=True)),
                ('adeuda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Documentacion')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('taller', models.BooleanField(default=False)),
                ('carga_horaria', models.IntegerField(blank=True, default=0, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Carrera')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso')),
                ('docente_provisional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Provisional', to='alcal.Docente')),
                ('docente_suplente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Suplente', to='alcal.Docente')),
                ('docente_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Titular', to='alcal.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fnac', models.DateField(blank=True, null=True)),
                ('num_dni', models.IntegerField(blank=True, null=True)),
                ('domicilio_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio_numero', models.IntegerField(blank=True, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_3', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pais_de_nacimiento', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Tipos de DNI',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Padre')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Vinculo')),
            ],
        ),
        migrations.AddField(
            model_name='padre',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('F', 'Felicitación'), ('O', 'Observación'), ('A', 'Apercibimiento'), ('N', 'Notificación'), ('C', 'Cambio de horario')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
                ('informante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotaParcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, null=True)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Materia')),
            ],
            options={
                'verbose_name_plural': 'Notas Parciales',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('instancia', models.CharField(choices=[('PT', 'Primer Trimestre'), ('ST', 'Segundo Trimestre'), ('TT', 'Tercer Trimestre'), ('CF', 'Calificación Final'), ('CD', 'Calificación Definitiva'), ('ND', 'Nota Diciembre'), ('NF', 'Nota Febrero'), ('MA', 'Mesa Adicional')], max_length=20, null=True)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=2)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(null=True)),
                ('tipo', models.CharField(choices=[('t', 'Llegada tarde'), ('T', 'Llegada tarde fuera de hora'), ('A', 'Ausente'), ('r', 'Retirado dentro de la última hora'), ('R', 'Retirado'), ('E', 'Ausente a Educación Física')], max_length=20)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=20)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='FechaAltaBaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('B', 'Baja'), ('A', 'Alta')], max_length=20)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni'),
        ),
        migrations.AddField(
            model_name='docente',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero', verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni'),
        ),
    ]
