# Generated by Django 2.1.5 on 2019-01-29 11:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_registro', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('antiguedad_meses', models.IntegerField()),
                ('antiguedad_anios', models.IntegerField()),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('num_dni', models.IntegerField()),
                ('domicilio_calle', models.CharField(max_length=100)),
                ('domicilio_numero', models.IntegerField()),
                ('telefono', models.CharField(max_length=100)),
                ('anio_ingreso', models.IntegerField()),
                ('fnac', models.DateField()),
                ('pais_de_nacimiento', django_countries.fields.CountryField(max_length=2)),
                ('telefono_1', models.CharField(max_length=100)),
                ('telefono_2', models.CharField(max_length=100)),
                ('telefono_3', models.CharField(max_length=100)),
                ('carrera_doncente', models.ManyToManyField(to='alcal.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('activx', models.BooleanField(default=True)),
                ('orden', models.IntegerField()),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fnac', models.DateField()),
                ('libro', models.CharField(max_length=5)),
                ('folio', models.IntegerField()),
                ('num_dni', models.IntegerField()),
                ('domicilio_calle', models.CharField(max_length=100)),
                ('domicilio_numero', models.IntegerField()),
                ('telefono_1', models.CharField(max_length=100)),
                ('telefono_2', models.CharField(max_length=100)),
                ('telefono_3', models.CharField(max_length=100)),
                ('anio_ingreso', models.IntegerField()),
                ('grupo_tec', models.IntegerField()),
                ('observacion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('nombre_de_adulto_responsable', models.CharField(max_length=200)),
                ('pais_de_nacimiento', django_countries.fields.CountryField(max_length=2)),
                ('profesion', models.CharField(max_length=100)),
                ('ficha_de_inscripcion', models.BooleanField()),
                ('foto_dni_estudiante', models.BooleanField()),
                ('foto_dni_estudiante_archivo', models.FileField(upload_to='')),
                ('foto_dni_responsable', models.BooleanField()),
                ('partida_de_nacimiento', models.BooleanField()),
                ('vacunas', models.BooleanField()),
                ('certificado', models.BooleanField()),
                ('url_foto', models.URLField()),
                ('archivo_de_seguimiento', models.URLField(null=True)),
                ('adeuda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcal.Documentacion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BA', 'Bachiller'), ('TE', 'Técnico')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Genero'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.TipoDni'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='vinculo_con_el_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Vinculo'),
        ),
        migrations.AddField(
            model_name='docente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Genero'),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.TipoDni'),
        ),
        migrations.AddField(
            model_name='curso',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Seccion'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Modalidad'),
        ),
    ]
