# Generated by Django 2.2.3 on 2020-01-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inasistencia',
            name='ed_fisica',
            field=models.CharField(choices=[('2', 'Llegada tarde'), ('2', 'Llegada tarde fuera de hora'), ('1', 'Ausente'), ('3', 'Retirado dentro de la última hora'), ('3', 'Retirado'), ('4', 'Sin Clase'), ('0', 'Presente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='maniana',
            field=models.CharField(choices=[('2', 'Llegada tarde'), ('2', 'Llegada tarde fuera de hora'), ('1', 'Ausente'), ('3', 'Retirado dentro de la última hora'), ('3', 'Retirado'), ('4', 'Sin Clase'), ('0', 'Presente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='tarde',
            field=models.CharField(choices=[('2', 'Llegada tarde'), ('2', 'Llegada tarde fuera de hora'), ('1', 'Ausente'), ('3', 'Retirado dentro de la última hora'), ('3', 'Retirado'), ('4', 'Sin Clase'), ('0', 'Presente')], max_length=20, null=True),
        ),
    ]
