# Generated by Django 2.2.3 on 2019-07-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='anio_ingreso',
            field=models.IntegerField(blank=True, default=2019, null=True),
        ),
    ]
