# Generated by Django 2.1.5 on 2019-01-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('BA', 'Bachiller'), ('TE', 'Técnico')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Modalidad',
        ),
    ]
