# Generated by Django 2.2.3 on 2019-08-21 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0002_auto_20190821_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 24, 16, 46, 14, 232156), null=True),
        ),
    ]
