# Generated by Django 2.2.3 on 2019-08-21 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0003_auto_20190821_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesapendiente',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 24, 16, 48, 20, 335413), null=True),
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
