# Generated by Django 2.1.5 on 2019-01-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0003_auto_20190129_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=2)),
                ('instancia', models.CharField(choices=[('NT', 'Nota Parcial'), ('PT', 'Primer Trimestre'), ('ST', 'Segundo Trimestre'), ('TT', 'Tercer Trimestre'), ('CF', 'Calificación Final'), ('CD', 'Calificación Definitiva'), ('ND', 'Nota Diciembre'), ('NF', 'Nota Febrero'), ('MA', 'Mesa Adicional')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcal.Curso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Materia'),
        ),
    ]
