# Generated by Django 2.2.3 on 2019-08-02 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0003_auto_20190802_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cursosiguiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alcal.Curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 5, 19, 25, 25, 43252), null=True),
        ),
    ]
