# Generated by Django 2.1.5 on 2019-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0004_auto_20190129_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='legajo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
