# Generated by Django 2.2.3 on 2019-08-03 00:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0004_auto_20190802_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 5, 21, 26, 26, 959273), null=True),
        ),
    ]
