# Generated by Django 2.2.3 on 2020-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0004_auto_20200129_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
