# Generated by Django 2.2.3 on 2019-08-21 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0004_auto_20190821_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 24, 16, 48, 38, 548696), null=True),
        ),
    ]
