# Generated by Django 2.2.3 on 2020-02-18 13:03

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0005_auto_20200130_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inasistencia',
            name='ed_fisica',
        ),
        migrations.RemoveField(
            model_name='inasistencia',
            name='maniana',
        ),
        migrations.RemoveField(
            model_name='inasistencia',
            name='tarde',
        ),
        migrations.AddField(
            model_name='inasistencia',
            name='tipo',
            field=models.CharField(choices=[('2', 'Llegada tarde'), ('2', 'Llegada tarde fuera de hora'), ('1', 'Ausente'), ('3', 'Retirado dentro de la última hora'), ('3', 'Retirado'), ('4', 'Sin Clase'), ('0', 'Presente')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inasistencia',
            name='turno',
            field=models.IntegerField(choices=[(0, 'Mañana'), (1, 'Tarde'), (2, 'Ed. Física')], null=True),
        ),
        migrations.AlterField(
            model_name='notaparcial',
            name='curso',
            field=models.ForeignKey(default='1A', on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso'),
        ),
        migrations.AlterField(
            model_name='notaparcial',
            name='estudiante',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='curso', chained_model_field='curso', on_delete=django.db.models.deletion.CASCADE, to='alcal.Estudiante'),
        ),
    ]
