# Generated by Django 2.1.5 on 2019-01-29 13:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0005_auto_20190129_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='activx',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='anio_ingreso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='certificado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcal.Curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio_calle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio_numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ficha_de_inscripcion',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='folio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto_dni_estudiante',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto_dni_estudiante_archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto_dni_responsable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcal.Genero'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo_tec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='libro',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_de_adulto_responsable',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='num_dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='observacion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='orden',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pais_de_nacimiento',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='partida_de_nacimiento',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='profesion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcal.TipoDni'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='url_foto',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='vacunas',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='vinculo_con_el_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcal.Vinculo'),
        ),
    ]
