# Generated by Django 2.2.3 on 2019-08-03 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0005_auto_20190802_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 5, 21, 26, 56, 529700), null=True),
        ),
        migrations.DeleteModel(
            name='Parentezco',
        ),
    ]
