# Generated by Django 2.2.3 on 2019-08-21 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0005_auto_20190821_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 24, 16, 51, 3, 806227), null=True),
        ),
    ]
