# Generated by Django 2.2.3 on 2019-08-21 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0006_auto_20190821_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesapendiente',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Periodo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 24, 16, 51, 23, 940410), null=True),
        ),
    ]
