# Generated by Django 2.2.3 on 2019-08-06 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0006_auto_20190802_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDeCuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 8, 23, 50, 8, 688452), null=True),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('importe', models.IntegerField()),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
                ('motivo_de_cuota', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.MotivoDeCuota')),
            ],
        ),
    ]
