# Generated by Django 2.2.3 on 2020-04-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0006_auto_20200218_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maniana', models.BooleanField(default=False)),
                ('tarde', models.BooleanField(default=False)),
                ('ed_fisica', models.BooleanField(default=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso')),
            ],
        ),
    ]
