# Generated by Django 2.1.5 on 2019-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0006_auto_20190129_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(max_length=5, verbose_name='Divisón'),
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
