# Generated by Django 2.2.3 on 2020-04-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0007_turnos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turnos',
            new_name='Turno',
        ),
    ]
