# Generated by Django 2.2.3 on 2019-08-06 02:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0007_auto_20190805_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Vinculo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 8, 23, 52, 33, 416171), null=True),
        ),
    ]
