# Generated by Django 2.1.5 on 2019-01-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0007_auto_20190129_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(null=True)),
                ('tipo', models.CharField(choices=[('t', 'Llegada tarde'), ('T', 'Llegada tarde fuera de hora'), ('A', 'Ausente'), ('R', 'Retirado'), ('E', 'Ausente a Educación Física')], max_length=20)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tipodni',
            options={'verbose_name_plural': 'Tipos de DNI'},
        ),
        migrations.AlterField(
            model_name='carrera',
            name='anios',
            field=models.IntegerField(verbose_name='Años de carrera'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='anio_ingreso',
            field=models.IntegerField(verbose_name='Año de Ingreso'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='antiguedad_anios',
            field=models.IntegerField(verbose_name='Antigüedad (Años)'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='antiguedad_meses',
            field=models.IntegerField(verbose_name='Antigüedad (Meses)'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='domicilio_numero',
            field=models.IntegerField(verbose_name='Domicilio Número'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fnac',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='num_dni',
            field=models.IntegerField(verbose_name='Número de Documento'),
        ),
    ]
