# Generated by Django 2.2.3 on 2019-08-21 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0007_auto_20190821_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesapendiente',
            name='pendiente',
        ),
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 24, 17, 30, 53, 128260), null=True),
        ),
        migrations.CreateModel(
            name='InscripcionPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.MesaPendiente')),
                ('pendiente', smart_selects.db_fields.ChainedManyToManyField(chained_field='mesa', chained_model_field='mesa', to='alcal.Pendiente')),
            ],
        ),
    ]
