# Generated by Django 2.2.3 on 2020-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0008_auto_20200415_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='ed_fisica',
            field=models.CharField(choices=[('2', 'Llegada tarde'), ('2', 'Llegada tarde fuera de hora'), ('1', 'Ausente'), ('3', 'Retirado dentro de la última hora'), ('3', 'Retirado'), ('4', 'Sin Clase'), ('0', 'Presente')], default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='maniana',
            field=models.CharField(choices=[('2', 'Llegada tarde'), ('2', 'Llegada tarde fuera de hora'), ('1', 'Ausente'), ('3', 'Retirado dentro de la última hora'), ('3', 'Retirado'), ('4', 'Sin Clase'), ('0', 'Presente')], default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tarde',
            field=models.CharField(choices=[('2', 'Llegada tarde'), ('2', 'Llegada tarde fuera de hora'), ('1', 'Ausente'), ('3', 'Retirado dentro de la última hora'), ('3', 'Retirado'), ('4', 'Sin Clase'), ('0', 'Presente')], default=0, max_length=5, null=True),
        ),
    ]
