# Generated by Django 2.1.5 on 2019-01-29 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0008_auto_20190129_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion', models.TextField()),
                ('fecha', models.DateField(default=datetime.datetime(2019, 1, 29, 17, 28, 4, 161860))),
                ('tipo', models.CharField(choices=[('F', 'Felicitación'), ('O', 'Observación'), ('A', 'Apercibimiento'), ('N', 'Notificación'), ('C', 'Cambio de horario')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcal.Estudiante')),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.AddField(
            model_name='inasistencia',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcal.Estudiante'),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
