# Generated by Django 2.2.3 on 2019-08-06 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alcal', '0008_auto_20190805_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='porcentaje_beca',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 9, 13, 53, 53, 837058), null=True),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('CM', 'Cambio de modalidad'), ('POI', 'Pase a otra institución'), ('IN', 'Inasistencias'), ('SS', 'Situación de Salud'), ('B', 'Becas'), ('CC', 'Cuestiones de Convivencia'), ('CO', 'Convocatoria'), ('SA', 'Situación académica'), ('SPF', 'Situación personal/familiar'), ('R', 'Reconocimiento')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
                ('informante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
