# Generated by Django 2.2.3 on 2019-08-22 01:59

import datetime
from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0008_auto_20190821_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionpendiente',
            name='pendiente',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='mesa', chained_model_field='pendiente', to='alcal.Pendiente'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 24, 22, 59, 4, 822869), null=True),
        ),
    ]
