# Generated by Django 2.2.3 on 2019-08-06 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('alcal', '0009_auto_20190806_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotivoDeCuota',
            new_name='NombreCuota',
        ),
        migrations.RenameField(
            model_name='cuota',
            old_name='motivo_de_cuota',
            new_name='nombre_cuota',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 9, 13, 59, 30, 839166), null=True),
        ),
    ]
