# Generated by Django 2.1.5 on 2019-01-29 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0009_auto_20190129_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 1, 29, 17, 29, 47, 378146)),
        ),
    ]
