# Generated by Django 2.2.3 on 2019-08-23 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0009_auto_20190821_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inasistencia',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 26, 16, 50, 15, 195680), null=True),
        ),
    ]
