# Generated by Django 2.1.5 on 2019-01-29 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0010_auto_20190129_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 1, 29, 17, 30, 56, 268483, tzinfo=utc)),
        ),
    ]
