# Generated by Django 2.2.3 on 2019-08-23 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0010_auto_20190823_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 26, 16, 50, 29, 482668), null=True),
        ),
    ]
