# Generated by Django 2.2.3 on 2019-08-06 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0011_auto_20190806_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 9, 14, 28, 46, 129837), null=True),
        ),
    ]
