# Generated by Django 2.2.3 on 2019-08-23 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0011_auto_20190823_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='inasistencia',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='estudiante',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='curso', chained_model_field='curso', on_delete=django.db.models.deletion.CASCADE, to='alcal.Estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2007, 8, 26, 17, 8, 57, 50931), null=True),
        ),
    ]
