# Generated by Django 2.1.5 on 2019-01-29 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0011_auto_20190129_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 1, 29, 17, 31, 32, 542225, tzinfo=utc)),
        ),
    ]
