# Generated by Django 2.1.5 on 2019-01-29 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0012_auto_20190129_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
