# Generated by Django 2.1.5 on 2019-02-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0014_notificacion_informante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='adeuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Documentacion'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='vinculo_con_el_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Vinculo'),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Carrera'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Docente'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Materia'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante'),
        ),
    ]
