# Generated by Django 2.1.5 on 2019-02-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0015_auto_20190209_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='instancia',
            field=models.CharField(choices=[('NT', 'Nota Parcial'), ('PT', 'Primer Trimestre'), ('ST', 'Segundo Trimestre'), ('TT', 'Tercer Trimestre'), ('CF', 'Calificación Final'), ('CD', 'Calificación Definitiva'), ('ND', 'Nota Diciembre'), ('NF', 'Nota Febrero'), ('MA', 'Mesa Adicional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Materia'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='numero',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
