# Generated by Django 2.1.5 on 2019-02-10 17:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0016_auto_20190209_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='anio_ingreso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de Ingreso'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='antiguedad_anios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Antigüedad (Años)'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='antiguedad_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Antigüedad (Meses)'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='carrera_doncente',
            field=models.ManyToManyField(blank=True, null=True, to='alcal.Carrera'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='domicilio_calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='domicilio_numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Domicilio Número'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fnac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='num_dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='pais_de_nacimiento',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='profesion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='activx',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='adeuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Documentacion'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='anio_ingreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='archivo_de_seguimiento',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='certificado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio_calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ficha_de_inscripcion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fnac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto_dni_estudiante',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto_dni_estudiante_archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto_dni_responsable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo_tec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='libro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_de_adulto_responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='num_dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pais_de_nacimiento',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='partida_de_nacimiento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='url_foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='vacunas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='vinculo_con_el_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Vinculo'),
        ),
    ]
