# Generated by Django 2.1.5 on 2019-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0017_auto_20190210_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carga_horaria',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
