# Generated by Django 2.1.5 on 2019-07-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0019_auto_20190723_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasAltaBaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('B', 'Baja'), ('A', 'Alta')], max_length=20)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Estudiante')),
            ],
        ),
        migrations.AlterModelOptions(
            name='documentacion',
            options={'verbose_name_plural': 'Documentaciones'},
        ),
        migrations.AlterModelOptions(
            name='notaparcial',
            options={'verbose_name_plural': 'Notas Parciales'},
        ),
    ]
