# Generated by Django 2.1.5 on 2019-07-23 21:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0020_auto_20190723_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fnac', models.DateField(blank=True, null=True)),
                ('libro', models.CharField(blank=True, max_length=5, null=True)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('num_dni', models.IntegerField(blank=True, null=True)),
                ('domicilio_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio_numero', models.IntegerField(blank=True, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_3', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_ingreso', models.IntegerField(blank=True, null=True)),
                ('grupo_tec', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_de_adulto_responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('pais_de_nacimiento', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('ficha_de_inscripcion', models.BooleanField(blank=True, null=True)),
                ('foto_dni_estudiante', models.BooleanField(blank=True, null=True)),
                ('foto_dni_estudiante_archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('foto_dni_responsable', models.BooleanField(blank=True, null=True)),
                ('partida_de_nacimiento', models.BooleanField(blank=True, null=True)),
                ('vacunas', models.BooleanField(blank=True, null=True)),
                ('certificado', models.BooleanField(blank=True, null=True)),
                ('url_foto', models.URLField(blank=True, null=True)),
                ('archivo_de_seguimiento', models.URLField(blank=True, null=True)),
                ('adeuda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Documentacion')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Genero')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.TipoDni')),
                ('vinculo_con_el_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alcal.Vinculo')),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='tipo',
            field=models.CharField(choices=[('t', 'Llegada tarde'), ('T', 'Llegada tarde fuera de hora'), ('A', 'Ausente'), ('r', 'Retirado dentro de la última hora'), ('R', 'Retirado'), ('E', 'Ausente a Educación Física')], max_length=20),
        ),
    ]
