# Generated by Django 2.1.5 on 2019-07-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0023_parentezco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre_de_adulto_responsable',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='pais_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='vinculo_con_el_estudiante',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='docente',
        ),
        migrations.AddField(
            model_name='materia',
            name='docente_provisional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Provisional', to='alcal.Docente'),
        ),
        migrations.AddField(
            model_name='materia',
            name='docente_suplente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Suplente', to='alcal.Docente'),
        ),
        migrations.AddField(
            model_name='materia',
            name='docente_titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Titular', to='alcal.Docente'),
        ),
    ]
