# Generated by Django 2.1.5 on 2019-07-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcal', '0024_auto_20190723_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='docente_provisional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Provisional', to='alcal.Docente'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente_suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Suplente', to='alcal.Docente'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='docente_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Titular', to='alcal.Docente'),
        ),
    ]
